In [12]:
# 归一化
from sklearn.preprocessing import MinMaxScaler

In [13]:
X = [[2, 1], [3, 1], [1, 4], [2, 6]]
scaler = MinMaxScaler(feature_range=(-1, 1))
# X_scaler = scaler.fit(X)
# X = X_scaler.transform(X)
X_scaler = scaler.fit_transform(X)
print(X_scaler)

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


In [14]:
# 标准化
from sklearn.preprocessing import StandardScaler
X = [[2, 1], [3, 1], [1, 4], [2, 6]]
scaler = StandardScaler()
X_scaler = scaler.fit_transform(X)
print(X_scaler)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [15]:
# 验证标准化的结果
import numpy as np
x = np.array(X)
# 均值
mean = x.mean(axis=0)
mean

array([2., 3.])

In [16]:
# 标准差
std = x.std(axis=0)
std

array([0.70710678, 2.12132034])

In [17]:
# 标准化计算
x_std = (x - mean) / std
print(x_std)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
